#!/usr/bin/env python3
"""Per-node soft placement regions for the node array, derived from a previous placement.

ACE places a node's MLP72 / BRAM72K column well (a 32-stage chain = one BMLP column, 17 rows) but scatters the node's
RLB logic over the die once many nodes compete, and the long control nets then miss 725 MHz
(docs/PI0_CLOCK_PLAN_20260917.md §3.1).  This turns the hard-block sites ACE chose in pass 1 into a soft region
per node for pass 2: a box of RLB tiles around the node's BMLP column(s), so its logic stays beside its column.

  1. dump pass-1 placement:   ace -batch -script_file <(echo 'restore_project ...; restore_impl <placed.acxdb>;
                              foreach i [find -insts {u_array.g_node_*}] { puts "$i [get_placement $i]" }')
     (paper/synth/dump_placement.tcl does it; instance prefix per top: chip_top fit = u., S0/S2 top = u_array.)
  2. python3 gen_node_regions.py <dump> --prefix u_array --out regions.pdc [--margin-x 12 --margin-y 24]

Tile geometry measured on the AC7t1500 from the half-array placement (m14v4x2r, 2026-09-17):
  RLB y ~ 7.49 * (bmlp_row + 0.5 * mlp_index) + 32.8,   RLB x ~ 5.16 * bmlp_col - 0.9   (residual < 15 / 5 tiles)
"""
from __future__ import annotations
import argparse, collections, re
from pathlib import Path

AY, BY, AX, BX = 7.49, 32.8, 5.16, -0.9
X_MIN, X_MAX, Y_MIN, Y_MAX = 27, 171, 46, 287       # fallback RLB extent; the dump's own L[x][y] sites widen it


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("dump", type=Path)
    ap.add_argument("--prefix", default="u_array", help="instance prefix of pi0_chip_top in the netlist (u for chip_top fits)")
    ap.add_argument("--emit-prefix", default=None, help="prefix to write into the regions (default: --prefix); "
                    "lets a chip-fit placement (u.) seed an S0/S2 build (u_array.)")
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--margin-x", type=int, default=12)
    ap.add_argument("--margin-y", type=int, default=24)
    ap.add_argument("--hard", action="store_true", help="inclusive regions instead of soft")
    a = ap.parse_args()
    pat = re.compile(rf"^i:{re.escape(a.prefix)}\.g_node_(\d+)__g_(chain|vector)_u_node\S*\s+(\S+)")
    sites = collections.defaultdict(list)
    kinds = {}
    xmin, xmax, ymin, ymax = X_MIN, X_MAX, Y_MIN, Y_MAX
    for line in a.dump.read_text().split("\n"):
        m = pat.match(line)
        if not m:
            continue
        node = int(m.group(1)); kinds[node] = m.group(2)
        l = re.search(r"x_core\.L\[(\d+)\]\[(\d+)\]", m.group(3))
        if l:
            xmin = min(xmin, int(l.group(1))); xmax = max(xmax, int(l.group(1)))
            ymin = min(ymin, int(l.group(2))); ymax = max(ymax, int(l.group(2)))
        s = re.search(r"x_core\.BMLP\[(\d+)\]\[(\d+)\]\.logic\.bmlp\.(mlp|bram)\[(\d+)\]", m.group(3))
        if s:
            sites[node].append((int(s.group(1)), int(s.group(2)), int(s.group(4)), s.group(3)))
    lines = ["# per-node soft placement regions generated by paper/synth/gen_node_regions.py from " + str(a.dump), ""]
    for node in sorted(sites):
        # a chain's column is where its MLP72 stages are (its writer FIFO BRAMs may land far off: let the soft
        # region pull them in); a vector node has 4 MLP72 and 68 BRAM72K, so every hard site counts there
        core = [s for s in sites[node] if s[3] == "mlp"] if kinds[node] == "chain" else sites[node]
        cols = collections.Counter(c for c, r, i, k in core)
        main_cols = [c for c, n in cols.items() if n >= 0.15 * len(core)] or [cols.most_common(1)[0][0]]
        rows = [r + 0.5 * i for c, r, i, k in core if c in main_cols]
        x0 = int(AX * min(main_cols) + BX) - a.margin_x; x1 = int(AX * max(main_cols) + BX) + a.margin_x
        y0 = int(AY * min(rows) + BY) - a.margin_y;      y1 = int(AY * max(rows) + BY) + a.margin_y
        x0, x1 = max(xmin, x0), min(xmax, x1); y0, y1 = max(ymin, y0), min(ymax, y1)
        name = f"rg_node{node}_{kinds[node]}"
        inst = f"{a.emit_prefix or a.prefix}.g_node_{node}__g_{kinds[node]}_u_node.*"
        lines.append(f"# node {node} {kinds[node]}: BMLP cols {sorted(main_cols)} rows {min(rows):.1f}-{max(rows):.1f} ({len(sites[node])} hard sites)")
        lines.append(f"create_region {{{name}}} {{{x0} {y0} {x1} {y1}}} {'' if a.hard else '-soft '}-snap tiles")
        lines.append(f"add_region_find_insts {{{name}}} {{find -insts {{{inst}}}}}")
        lines.append("")
    a.out.write_text("\n".join(lines))
    print(f"{len(sites)} node regions -> {a.out} (RLB extent x {xmin}-{xmax} y {ymin}-{ymax})")


if __name__ == "__main__":
    main()
