# -------------------------------------------------------------------------
# Synplify timing constaint file
# All clocks and clock relationships should be defined in this file for synthesis
# Note : There are small differences between Synplify Pro and ACE SDC syntax
# therefore it is not recommended to use the same file for both, instead to
# have two separate files.
# -------------------------------------------------------------------------

# -------------------------------------------------------------------------
# Primary clock timing constraints
# -------------------------------------------------------------------------
# Keep synthesis clock assumptions aligned with the ACE IO-ring SDC.
# The high-speed matrix core uses i_mlp_clk; the NAP/NoC fabric clock is
# generated by u_acx_clkdiv as divide-by-2 from i_mlp_clk.
# The clock names must match the ones the ACE IO-ring SDC declares on these
# same ports, because that file is read after this one and its create_clock
# overrides the source pin.  Naming a clock "mlp_clk" here left it undefined
# ("MT661: Clock reg_clk is overridden on all sources and thus undefined"),
# which in turn silently dropped every set_false_path below with
# "none of the '-from' objects specified by the constraint exist".
# 8.0 ns = 125 MHz.  This must track src/acxip/pll_nap.acxip's
# float_target_out0_frequency, which is what actually programs PLL_SW_1 and so
# is what the silicon will run at.  The original 1.3333 ns / 750 MHz was never
# reachable - builds measured 170.9, 175.6 and 175.6 MHz - so a bitstream built
# against it was clocked about four times faster than its own longest path and
# could not have worked on a board whatever the timing report said.
#
# A correction, because the first attempt at this got the reasoning wrong.
# Moving to 4.0 ns / 250 MHz was also justified on the grounds that a target
# every path misses leaves place-and-route unable to tell a critical path from
# an ordinary one.  That turned out to be false for this design.  Build A,
# impl_pi0_t2_q1r4_98f45c5e2a4f_20260816T190030Z, measured i_mlp_clk going DOWN
# from 175.6 to 160.1 MHz on the relaxed target, and i_mcu_clk down from 141.7
# to 129.5 inside vendor IP that was not touched at all.  Every critical path
# that survives in this design is interconnect rather than logic - 0 to 1 logic
# levels carrying 6 to 11 ns of net delay - and on paths like that the placer's
# willingness to shorten a wire is the entire mechanism.  Relax the target and
# it optimises total wirelength instead.
#
# So the two concerns are separated: this period, and the PLL, are what the
# silicon runs at, while the placer is pushed harder through
# set_clock_uncertainty in src/constraints/ace_constraints.sdc, which ACE reads
# after the generated IO-ring SDC.
set MLPCLK_PERIOD 6.667
create_clock -name i_mlp_clk [get_ports i_mlp_clk] -period $MLPCLK_PERIOD

set NAPCLK_DIVIDE 2
create_generated_clock -name nap_clk \
    -source [get_ports i_mlp_clk] \
    -divide_by $NAPCLK_DIVIDE \
    [get_pins u_acx_clkdiv/clk_out]

set MCUCLK_PERIOD 10.0
create_clock -name i_mcu_clk [get_ports i_mcu_clk] -period $MCUCLK_PERIOD

set REGCLK_PERIOD 15.500
create_clock -name i_reg_clk [get_ports i_reg_clk] -period $REGCLK_PERIOD


# -------------------------------------------------------------------------
# Example of defining a generated clock
# -------------------------------------------------------------------------
# create_generated_clock -name clk_gate [ get_pins {i_clkgate/clk_out} ] -source  [get_ports {i_clk} ] -divide_by 1

# -------------------------------------------------------------------------
# Create asynchronous clock groups as more than one clock
# -------------------------------------------------------------------------
# mlp_clk and nap_clk are related. Register/MMIO and MCU domains are
# asynchronous to the matrix/NoC datapath clocks.
set_clock_groups -asynchronous -group {i_mlp_clk nap_clk} \
                               -group {i_reg_clk} \
                               -group {i_mcu_clk}

set_false_path -from [get_clocks i_reg_clk] -to [get_clocks i_mlp_clk]
set_false_path -from [get_clocks i_reg_clk] -to [get_clocks nap_clk]
set_false_path -from [get_clocks i_reg_clk] -to [get_clocks i_mcu_clk]
set_false_path -from [get_clocks i_mlp_clk] -to [get_clocks i_reg_clk]
set_false_path -from [get_clocks nap_clk]   -to [get_clocks i_reg_clk]
set_false_path -from [get_clocks i_mcu_clk] -to [get_clocks i_reg_clk]
set_false_path -from [get_clocks i_mcu_clk] -to [get_clocks i_mlp_clk]
set_false_path -from [get_clocks i_mcu_clk] -to [get_clocks nap_clk]
set_false_path -from [get_clocks i_mlp_clk] -to [get_clocks i_mcu_clk]
set_false_path -from [get_clocks nap_clk]   -to [get_clocks i_mcu_clk]
# The *all_write_done cells this used to except no longer exist anywhere in
# src/rtl, so the constraint only produced an "objects do not exist" error.
