#######################################
# ACE GENERATED SDC FILE
# Generated on: 2026.09.16 at 07:52:11 PDT
# By: ACE 10.5.2
# From project: tc_ref_design_top
#######################################
# IO Ring Boundary SDC Clock Groups File
#######################################
# The following clock groups should be used as a template. You can copy and paste from this file into your SDC file.
# Do NOT include this file in your ACE project directly.
# Do NOT edit this file since it's an auto-generated file.

set_clock_groups -name "i_reg_clk_cg" -asynchronous -group {i_reg_clk}
set_clock_groups -name "i_mcu_clk_cg" -asynchronous -group {i_mcu_clk}
set_clock_groups -name "i_mlp_clk_cg" -asynchronous -group {i_mlp_clk}

######################################
# End IO Ring Boundary SDC Clock Groups File
######################################
